name: supply_chain_app
description: "A new Flutter project."
publish_to: 'none'  # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.9

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/wakdukaan_logo.png
    - assets/image/Airpods.png
    - assets/image/charger.png
    - assets/image/headsets.png
    - assets/image/ladies watch.png
    - assets/image/men watch.png

