// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hV6syIThHLhdEIouCq1byXJ0tMScnDM',
    appId: '1:306071655231:web:03539a8eebe7dd44f9b98a',
    messagingSenderId: '306071655231',
    projectId: 'way-dukaan',
    authDomain: 'way-dukaan.firebaseapp.com',
    storageBucket: 'way-dukaan.firebasestorage.app',
    measurementId: 'G-1TCRWB2CJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfB3RSk_DscaQ1jzgWpqVsn-JGapDPHs',
    appId: '1:306071655231:android:52c2f51e99321a47f9b98a',
    messagingSenderId: '306071655231',
    projectId: 'way-dukaan',
    storageBucket: 'way-dukaan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ZfqwcOlFO8RzawIdq9SLNaPHU1sEC0Q',
    appId: '1:306071655231:ios:ae496d75205d9df7f9b98a',
    messagingSenderId: '306071655231',
    projectId: 'way-dukaan',
    storageBucket: 'way-dukaan.firebasestorage.app',
    iosBundleId: 'com.example.supplyChainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ZfqwcOlFO8RzawIdq9SLNaPHU1sEC0Q',
    appId: '1:306071655231:ios:ae496d75205d9df7f9b98a',
    messagingSenderId: '306071655231',
    projectId: 'way-dukaan',
    storageBucket: 'way-dukaan.firebasestorage.app',
    iosBundleId: 'com.example.supplyChainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2hV6syIThHLhdEIouCq1byXJ0tMScnDM',
    appId: '1:306071655231:web:505a0a1433fdccfef9b98a',
    messagingSenderId: '306071655231',
    projectId: 'way-dukaan',
    authDomain: 'way-dukaan.firebaseapp.com',
    storageBucket: 'way-dukaan.firebasestorage.app',
    measurementId: 'G-19R0VXQC3B',
  );

}